name: Infra CI & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  migrate:
    name: Apply Supabase Migrations
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set Up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Link & Apply Migrations
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF
          supabase db push
