name: Infra CI & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    name: Apply Supabase Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Link Supabase Project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Apply Migrations
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: supabase db push

  seed:
    name: Seed Database (Manual)
    runs-on: ubuntu-latest
    needs: migrate
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run Seed Script
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          psql \
            --host=$(echo "${{ secrets.SUPABASE_URL }}" | sed -E 's~https?://([^\.]+)\..*~db.\1.supabase.co~') \
            --username=postgres \
            --dbname=postgres \
            --file=seeds/seed.sql
