name: Seed Database

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Debug Environment Variables
        run: |
          echo "Using SUPABASE_DB_URL: $SUPABASE_DB_URL"
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

      - name: Run Seed Script
        run: |
          set -e
          psql "$SUPABASE_DB_URL?sslmode=require" -f supabase/seeds/seed.sql